/**
 * Login API
 * API description for Login method in Markdown.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserLoginApiForm {
  
  @SerializedName("gaId")
  private String gaId = null;
  @SerializedName("adId")
  private String adId = null;
  @SerializedName("apnId")
  private String apnId = null;
  @SerializedName("gcmId")
  private String gcmId = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("phoneCc")
  private String phoneCc = null;
  @SerializedName("uuid")
  private String uuid = null;
  @SerializedName("authcode")
  private String authcode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGaId() {
    return gaId;
  }
  public void setGaId(String gaId) {
    this.gaId = gaId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAdId() {
    return adId;
  }
  public void setAdId(String adId) {
    this.adId = adId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getApnId() {
    return apnId;
  }
  public void setApnId(String apnId) {
    this.apnId = apnId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getGcmId() {
    return gcmId;
  }
  public void setGcmId(String gcmId) {
    this.gcmId = gcmId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPhoneCc() {
    return phoneCc;
  }
  public void setPhoneCc(String phoneCc) {
    this.phoneCc = phoneCc;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthcode() {
    return authcode;
  }
  public void setAuthcode(String authcode) {
    this.authcode = authcode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserLoginApiForm userLoginApiForm = (UserLoginApiForm) o;
    return (this.gaId == null ? userLoginApiForm.gaId == null : this.gaId.equals(userLoginApiForm.gaId)) &&
        (this.adId == null ? userLoginApiForm.adId == null : this.adId.equals(userLoginApiForm.adId)) &&
        (this.apnId == null ? userLoginApiForm.apnId == null : this.apnId.equals(userLoginApiForm.apnId)) &&
        (this.gcmId == null ? userLoginApiForm.gcmId == null : this.gcmId.equals(userLoginApiForm.gcmId)) &&
        (this.name == null ? userLoginApiForm.name == null : this.name.equals(userLoginApiForm.name)) &&
        (this.password == null ? userLoginApiForm.password == null : this.password.equals(userLoginApiForm.password)) &&
        (this.phone == null ? userLoginApiForm.phone == null : this.phone.equals(userLoginApiForm.phone)) &&
        (this.phoneCc == null ? userLoginApiForm.phoneCc == null : this.phoneCc.equals(userLoginApiForm.phoneCc)) &&
        (this.uuid == null ? userLoginApiForm.uuid == null : this.uuid.equals(userLoginApiForm.uuid)) &&
        (this.authcode == null ? userLoginApiForm.authcode == null : this.authcode.equals(userLoginApiForm.authcode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.gaId == null ? 0: this.gaId.hashCode());
    result = 31 * result + (this.adId == null ? 0: this.adId.hashCode());
    result = 31 * result + (this.apnId == null ? 0: this.apnId.hashCode());
    result = 31 * result + (this.gcmId == null ? 0: this.gcmId.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.phoneCc == null ? 0: this.phoneCc.hashCode());
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.authcode == null ? 0: this.authcode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserLoginApiForm {\n");
    
    sb.append("  gaId: ").append(gaId).append("\n");
    sb.append("  adId: ").append(adId).append("\n");
    sb.append("  apnId: ").append(apnId).append("\n");
    sb.append("  gcmId: ").append(gcmId).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  phoneCc: ").append(phoneCc).append("\n");
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  authcode: ").append(authcode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
